import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static String trOf(BuildContext context, String key) {
    return of(context)?.translate(key) ?? key;
  }

  String translate(String key, {Map<String, String>? args}) {
    // Try current locale, then fallback to English, then the key itself
    String value = _localizedValues[locale.languageCode]?[key] ?? 
           _localizedValues['en']?[key] ?? 
           key;
    if (args != null) {
      args.forEach((k, v) {
        value = value.replaceAll('{$k}', v);
      });
    }
    return value;
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'settings': 'Settings',
      'map_location': 'Map & Location',
      'auto_detect': 'Auto-detect location',
      'auto_detect_sub': 'Show nearby stops automatically',
      'show_virtual_buses': 'Show virtual buses',
      'show_virtual_buses_sub': 'Animated bus positions on map',
      'map_style': 'Map style',
      'notifications': 'Notifications',
      'bus_arrival_alerts': 'Bus arrival alerts',
      'bus_arrival_alerts_sub': 'Get notified when bus is near',
      'app': 'App',
      'language': 'Language',
      'about_translink': 'About TransLink',
      'privacy_policy': 'Privacy Policy',
      'privacy_policy_sub': 'How we use your data',
      'version': 'Version 1.2.0 · Sri Lanka',
      'where_to': 'Where to?',
      'available_routes': 'Available Routes',
      'home': 'Home',
      'work': 'Work',
      'recent_searches': 'Recent Searches',
      'recents': 'Recents',
      'bus_detected': '🟢 Bus detected nearby',
      'waiting_for_bus': 'Waiting for bus...',
      'live': 'Live',
      'waiting': 'Waiting',
      // Nav Tabs
      'schedule_nav': 'Schedule',
      'explore_nav': 'Explore',
      'home_nav': 'Home',
      'saved_nav': 'Saved',
      'account_nav': 'Account',
      'nearby_stops': 'Nearby Stops',
      'quick_actions': 'Quick Actions',
      'active_ride': 'Active Ride',
      // Get Started
      'get_started': 'Get Started',
      'live_tracking': 'Live Tracking',
      'timetables': 'Timetables',
      'smart_routes': 'Smart Routes',
      'real_time_tracking': 'Real-time public transport tracking',
      'sri_lanka': 'Sri Lanka',
      // Login
      'welcome_back': 'Welcome back',
      'sign_in_continue': 'Sign in to continue',
      'username': 'Username',
      'email_address': 'Email address',
      'password': 'Password',
      'continue_btn': 'Continue',
      'create_account': 'Create Account',
      'continue_google': 'Continue with Google',
      'already_have_account': 'Already have an account? ',
      'sign_in': 'Sign In',
      'dont_have_account': "Don't have an account? ",
      'sign_up': 'Sign Up',
      'enter_email_pass': 'Please enter email and password',
      'enter_username': 'Please enter a username',
      'something_went_wrong': 'Something went wrong. Please try again.',
      'no_internet_msg': 'No internet connection. Please check your data or Wi-Fi.',
      'invalid_credentials': 'Invalid email or password. Please try again.',
      'google_login_failed': 'Google login failed. Please try again later.',
      'timeout_msg': 'Connection timed out. Please check your signal and try again.',
      'permission_denied_msg': 'Permission denied. Please check your account status.',
      'Theme Mode': 'Theme Mode',
      // Account additional
      'sign_out': 'Sign Out',
      'profile_info': 'Profile Info',
      'full_name': 'Full Name',
      'role': 'Role',
      'passenger': 'Passenger',
      'member_since': 'Member since',
      'edit_name': 'Edit Name',
      'save': 'Save',
      'cancel': 'Cancel',
      // Favourites
      'schedule_saved': 'Schedule & Saved',
      'timetable_tab': 'Timetable',
      'saved_routes_tab': 'Saved Routes',
      'nearby_bus_stops': 'Nearby Bus Stops',
      'min_walk': 'min walk',
      'view_board': 'View Board',
      'view_live_buses': 'View Live Buses',
      'no_stops_nearby': 'No stops nearby',
      'no_stops_sub': 'We couldn\'t find any bus stops within 2km.',
      'route_prefix': 'Route',
      'min_total': 'min total',
      'search_new_route': 'Search new route',
      'no_saved_routes': 'No saved routes',
      'no_saved_routes_sub': 'Tap the heart icon on any route to save it.',
      'could_not_open_maps': 'Could not open Google Maps',
      'approaching_stop': '🔔 Approaching Stop',
      'approaching_stop_msg': 'You are within 500m of your destination stop. Get ready to alight!',
      'ok': 'OK',
      'no_transit_options': 'No transit options for',
      'retry': 'Retry',
      'failed_load_routes': 'Failed to load routes. Try again.',
      'ride_active_label': 'Ride Active',
      'set_label': 'Set',
      'search_set_home': 'Search to set your Home location',
      'search_set_work': 'Search to set your Work location',
      'recent_label': 'Recent',
      'saved_routes_label': 'Saved routes',
      'no_saved_routes_msg': 'No saved routes yet. Tap the heart on a route to save it.',
      'live_label': 'Live',
      'walk_label': 'Walk',
      'to_stop_label': 'to',
      'bus_leg_label': 'Bus',
      'direct_to_dest': 'Direct to destination',
      'route_text': 'Route',
      'arrival_label': 'arrival',
      'no_live_buses': 'No live buses active right now',
      'no_active_corridor': 'No active buses on this corridor',
      'tracking_resume_msg': 'Real-time tracking will resume once a bus starts its trip.',
      'refresh_tracking': 'Refresh tracking',
      'journey_details': 'Journey details',
      'report_issue': 'Report an Issue',
      'set_remind_me': 'Set "Remind Me" Alert',
      'cancel_remind_me': 'Cancel "Remind Me" Alert',
      'alight_alert_set': 'Reminder set for 500m before destination.',
      'bus_approaching_pickup': 'Your bus is approaching your stop',
      'dest_near_msg': 'Your destination is within 500m',
      'how_crowded': 'How crowded is your bus?',
      'empty_label': '🟢 Empty',
      'standing_label': '🟡 Standing',
      'packed_label': '🔴 Packed',
      'thanks_reporting': 'Thanks for reporting crowd levels!',
      'passed_label': 'Passed',
      'today_label': 'Today',
      'current_label': 'Current',
      'from_label': 'From',
      'to_label': 'To',
      'next_departure': 'Next departure',
      'stop_timeline': 'Stop Timeline',
      'no_stops_available': 'No stops available',
      'stop_prefix': 'Stop',
      'username_updated': '✓ Username updated',
      'walk_to': 'Walk to',
      'bus_stand': 'bus stand',
      'nearest_stop': 'nearest stop',
      'duration_label': 'Duration',
      'distance_label': 'Distance',
      'est_fare_label': 'Est. Fare',
      'nearest_bus_stand': 'Nearest bus stand',
      'min_walk_label': 'min walk',
      'reported_msg': 'reported',
      'failed_report': 'Failed to submit report.',
      'status_label': 'Status',
      'heavy_traffic': 'Heavy Traffic',
      'road_closed': 'Road Closed',
      'overcrowded': 'Overcrowded',
      'dangerous_driving': 'Dangerous Driving',
      'report_issue_title': 'Report an Issue',
      'are_you_sure': 'Are you sure?',
      'close': 'Close',
      'minimize': 'Minimize',
      'minimize_ride': 'MINIMIZE RIDE',
      'style_standard': 'Standard',
      'style_satellite': 'Satellite (OSM)',
      'style_minimal': 'Minimal',
      'min': 'min',
      'total': 'total',
      'start_trip_btn': 'START ROUTE',
      'waiting_at_stops': 'passengers waiting at next stops',
      'stop_ride_btn': 'STOP RIDE',
      'stop_ride_confirm_title': 'Stop Journey?',
      'stop_ride_confirm_msg': 'Are you sure you want to stop this ride tracking?',
      'search_hint': 'Search destination...',
      'suggested_places': 'Suggested Places',
      'wallet_title': 'Wallet',
      'wallet_nav': 'Wallet',
      'available_balance': 'Available Balance',
      'recent_transactions': 'Recent Transactions',
      'top_up': 'Top Up',
      'passes': 'Passes',
      'offers': 'Offers',
      'pay_for_ride': 'PAY FOR RIDE',
      'wallet_info_title': 'TransLink Wallet',
      'wallet_info_msg': 'Your TransLink Wallet allows you to pay for bus rides securely using QR codes. You can link your credit/debit cards to top up your balance.',
      'voice_assist': 'Voice Assist',
      'arriving_in': 'Arriving in',
      'min_label': 'min',
      'quick_actions_title': 'Quick Actions',
      'passes_title': 'Passes & Travel Cards',
      'school_pass': 'School / Student Pass',
      'train_pass': 'Monthly Train Pass',
      'select_pass_type': 'Select Pass Type',
      'buy_pass_btn': 'Purchase Pass',
      'live_tracking_badge': 'Live Tracking',
      'mic_permission_required': 'Microphone permission is required for voice assist.',
      // Missing keys — must never show raw underscore text
      'recent_activity': 'Recent Activity',
      'top_up_method': 'Top Up Method',
      'link_new_card': 'Link New Card',
      'verified_account': 'verified account',
      'scan_to_pay': 'Scan to Pay Fare',
      'show_to_conductor': 'Show this to the conductor',
      'route_details': 'Route Details',
      'suggested_routes': 'Suggested Routes',
      'search_to_see_routes': 'Search for a destination to see routes',
      'walk_to_bus_stand': 'Walk to bus stand',
      'walk_to_destination': 'Walk to destination',
      'share_journey': 'Share Journey',
      'live_eta': 'Live Arrival',
      'bus_active_msg': 'Bus is active. Tracking...',
      'upcoming_arrivals': 'Upcoming Arrivals',
      'show_on_map': 'Show on Map',
      'eta_label': 'ETA',
      'on_time': 'On time',
      'delayed': 'Delayed',
      'cancelled': 'Cancelled',
      'no_upcoming_buses': 'No upcoming buses',
      'now_label': 'Now',
      'see_all': 'See All',
      'ai_support': 'AI Support',
      'map_view': 'Map View',
      'skip_nav': 'Skip',
      'next_nav': 'Next',
      'get_started_nav': "Let's Go!",
      // New Onboarding & Fleet
      'select_language': 'Select Language',
      'mixed_fleet': 'Mixed Fleet',
      'mixed_fleet_sub': 'Tracking both Private and CTB buses in real-time.',
      'intercity_express': 'Intercity Express',
      'intercity_express_sub': 'Reliable long-distance travel across Sri Lanka.',
      'ctb_label': 'CTB',
      'private_label': 'Private',
      'fleet_status': 'Fleet Status',
      'active_buses': 'Active Buses',
      'onboarding_payment_title': 'Digital Payments',
      'onboarding_payment_sub': 'Scan and pay using QR codes for a hassle-free journey.',
      'welcome_title': 'Welcome to TransLink',
      'welcome_sub': 'Your ultimate companion for public transport in Sri Lanka.',
      'starting_from_rs': 'Starting from Rs.',
      'no_stops_found': 'No bus stops found nearby.',
      'm_away': 'm away',
      'colombo_matara': 'Colombo - Matara',
      'colombo_galle': 'Colombo - Galle',
      'kaduwela_matara': 'Kaduwela - Matara',
      'makumbura_galle': 'Makumbura - Galle',
      'colombo_kandy': 'Colombo - Kandy',
      'payment_success_title': 'Payment Success',
      'payment_success_msg': 'Your e-ticket for Route {route} has been issued successfully.\n\nDo you want to continue tracking this journey?',
      'end_journey': 'End Journey',
      'continue_journey': 'Continue',
      'pay_label': 'PAY',
      'login_to_pay_qr': 'Please login to pay via QR',
      'swipe_tracking': 'Swipe up to see tracking details',
      'swipe_route_details': 'Swipe up to see full route details',
      'swipe_nearby': 'Swipe up for nearby buses & stops',
      'insufficient_balance_msg': 'Insufficient wallet balance. Please top up your wallet.',
    },
    'si': {
      'settings': 'සැකසුම්',
      'map_location': 'සිතියම සහ ස්ථානය',
      'auto_detect': 'ස්වයංක්‍රීයව ස්ථානය හඳුනාගන්න',
      'auto_detect_sub': 'අවට බස් නැවතුම් ස්වයංක්‍රීයව පෙන්වන්න',
      'show_virtual_buses': 'අතථ්‍ය බස් පෙන්වන්න',
      'show_virtual_buses_sub': 'සිතියමේ සජීවී බස් රථ පෙන්වන්න',
      'map_style': 'සිතියම් විලාසය',
      'notifications': 'දැනුම්දීම්',
      'bus_arrival_alerts': 'බස් පැමිණීමේ දැනුම්දීම්',
      'bus_arrival_alerts_sub': 'බස් රථයක් ආසන්න වූ විට දැනුම් දෙන්න',
      'app': 'යෙදුම',
      'language': 'භාෂාව',
      'about_translink': 'TransLink ගැන',
      'privacy_policy': 'පෞද්ගලිකත්ව ප්‍රතිපත්තිය',
      'privacy_policy_sub': 'අපි ඔබේ දත්ත භාවිතා කරන්නේ කෙසේද?',
      'version': 'අනුවාදය 1.2.0 · ශ්‍රී ලංකාව',
      'where_to': 'යන්නේ කොහේද?',
      'available_routes': 'ලබා ගත හැකි මාර්ග',
      'home': 'නිවස',
      'work': 'වැඩ',
      'recent_searches': 'මෑත සෙවුම්',
      'recents': 'මෑතකදී සොයන ලද',
      'bus_detected': '🟢 බස් රථයක් ආසන්නයේ ඇත',
      'waiting_for_bus': 'බස් රථය එනතෙක් බලා සිටී...',
      'live': 'සජීවී',
      'waiting': 'බලා සිටී',
      'schedule_nav': 'කාලසටහන',
      'explore_nav': 'ගවේෂණය',
      'home_nav': 'නිවස',
      'saved_nav': 'සුරකින ලද',
      'account_nav': 'ගිණුම',
      'nearby_stops': 'අසල නැවතුම්',
      'quick_actions': 'කෙටි ක්‍රියා',
      'active_ride': 'සක්‍රීය ගමන',
      'get_started': 'ආරම්භ කරන්න',
      'live_tracking': 'සජීවී ලුහුබැඳීම',
      'timetables': 'කාලසටහන්',
      'smart_routes': 'ස්මාර්ට් මාර්ග',
      'real_time_tracking': 'සජීවී පොදු ප්‍රවාහන ලුහුබැඳීම',
      'sri_lanka': 'ශ්‍රී ලංකාව',
      'welcome_back': 'යළිත් සාදරයෙන් පිළිගනිමු',
      'sign_in_continue': 'ඉදිරියට යාමට පුරන්න',
      'username': 'පරිශීලක නාමය',
      'email_address': 'විද්‍යුත් තැපැල් ලිපිනය',
      'password': 'මුරපදය',
      'continue_btn': 'ඉදිරියට යන්න',
      'create_account': 'ගිණුමක් සාදන්න',
      'continue_google': 'Google සමඟ ඉදිරියට යන්න',
      'already_have_account': 'දැනටමත් ගිණුමක් තිබේද? ',
      'sign_in': 'පිවිසෙන්න',
      'dont_have_account': "ගිණුමක් නැද්ද? ",
      'sign_up': 'ලියාපදිංචි වන්න',
      'enter_email_pass': 'කරුණාකර විද්‍යුත් තැපෑල සහ මුරපදය ඇතුළත් කරන්න',
      'enter_username': 'කරුණාකර පරිශීලක නාමයක් ඇතුළත් කරන්න',
      'something_went_wrong': 'යම් වැරදීමක් සිදු විය. කරුණාකර නැවත උත්සාහ කරන්න.',
      'no_internet_msg': 'අන්තර්ජාල සම්බන්ධතාවයක් නොමැත. කරුණාකර ඔබගේ දත්ත සම්බන්ධතාවය පරීක්ෂා කරන්න.',
      'invalid_credentials': 'විද්‍යුත් තැපෑල හෝ මුරපදය වැරදියි. කරුණාකර නැවත උත්සාහ කරන්න.',
      'google_login_failed': 'Google පුරනය වීම අසාර්ථක විය. කරුණාකර පසුව නැවත උත්සාහ කරන්න.',
      'timeout_msg': 'සම්බන්ධතාවය ප්‍රමාද වැඩිියි. ඔබගේ සංඥා පරීක්ෂා කර නැවත උත්සාහ කරන්න.',
      'permission_denied_msg': 'අවසර නැත. කරුණාකර ඔබගේ ගිණුම් තත්ත්වය පරීක්ෂා කරන්න.',
      'Theme Mode': 'තේමා මාදිලිය',
      'sign_out': 'ඉවත් වන්න',
      'profile_info': 'පැතිකඩ තොරතුරු',
      'full_name': 'සම්පූර්ණ නම',
      'role': 'කාර්යභාරය',
      'passenger': 'මගියෙකු',
      'member_since': 'සාමාජිකත්වය',
      'edit_name': 'නම වෙනස් කරන්න',
      'save': 'සුරකින්න',
      'cancel': 'අවලංගු කරන්න',
      'schedule_saved': 'කාලසටහන සහ සුරකින ලද',
      'timetable_tab': 'කාලසටහන',
      'saved_routes_tab': 'සුරකින ලද මාර්ග',
      'nearby_bus_stops': 'අවට බස් නැවතුම්',
      'min_walk': 'මිනිත්තු ඇවිදීමක්',
      'view_board': 'පුවරුව බලන්න',
      'no_stops_nearby': 'අවට නැවතුම් නොමැත',
      'no_stops_sub': '2km ක් ඇතුළත බස් නැවතුම් අපට සොයාගත නොහැකි විය.',
      'route_prefix': 'මාර්ගය',
      'min_total': 'සමස්ත මිනිත්තු',
      'search_new_route': 'නව මාර්ගයක් සොයන්න',
      'no_saved_routes': 'සුරකින ලද මාර්ග නොමැත',
      'no_saved_routes_sub': 'සුරැකීමට ඕනෑම මාර්ගයක හෘද නිරූපකය ඔබන්න.',
      'could_not_open_maps': 'Google Maps විවෘත කළ නොහැකි විය',
      'approaching_stop': '🔔 නැවතුමට ළඟා වේ',
      'approaching_stop_msg': 'ඔබ ඔබේ ගමනාන්ත නැවතුමේ සිට මීටර් 500ක් ඇතුළත සිටී. බැසීමට සූදානම් වන්න!',
      'ok': 'හරි',
      'no_transit_options': 'සඳහා ගමනාගමන විකල්ප නොමැත',
      'retry': 'නැවත උත්සාහ කරන්න',
      'failed_load_routes': 'මාර්ග පූරණය කිරීමට අපොහොසත් විය. නැවත උත්සාහ කරන්න.',
      'ride_active_label': 'ගමන සක්‍රීයයි',
      'set_label': 'සකසන්න',
      'search_set_home': 'ඔබේ නිවසේ ස්ථානය සැකසීමට සොයන්න',
      'search_set_work': 'ඔබේ රැකියාවේ ස්ථානය සැකසීමට සොයන්න',
      'recent_label': 'මෑතකාලීන',
      'saved_routes_label': 'සුරකින ලද මාර්ග',
      'no_saved_routes_msg': 'තවම සුරකින ලද මාර්ග නොමැත. සුරැකීමට මාර්ගයක හෘද සලකුණ ඔබන්න.',
      'live_label': 'සජීවී',
      'walk_label': 'ඇවිදීම',
      'to_stop_label': 'දක්වා',
      'bus_leg_label': 'බස් රථය',
      'direct_to_dest': 'කෙලින්ම ගමනාන්තයට',
      'route_text': 'මාර්ගය',
      'arrival_label': 'පැමිණීම',
      'no_live_buses': 'දැනට සජීවී බස් රථ සක්‍රිය නැත',
      'no_active_corridor': 'මෙම කොරිඩෝවේ සක්‍රීය බස් රථ නොමැත',
      'tracking_resume_msg': 'බස් රථයක් ගමන ආරම්භ කළ පසු සජීවී ලුහුබැඳීම නැවත ආරම්භ වේ.',
      'refresh_tracking': 'ලුහුබැඳීම යාවත්කාලීන කරන්න',
      'journey_details': 'ගමන් විස්තර',
      'report_issue': 'ගැටලුවක් වාර්තා කරන්න',
      'set_remind_me': '"Remind Me" ඇඟවීම සකසන්න',
      'cancel_remind_me': '"Remind Me" ඇඟවීම අවලංගු කරන්න',
      'alight_alert_set': 'මතක් කිරීම ගමනාන්තයට මීටර් 500කට පෙර සකසා ඇත.',
      'bus_approaching_pickup': 'බස් රථය ඔබගේ නැවතුමට පැමිණේ',
      'dest_near_msg': 'ඔබ ගමනාන්තයට මීටර් 500ක් ඇතුළත සිටී',
      'how_crowded': 'ඔබේ බස් රථයේ සෙනඟ කොපමණද?',
      'empty_label': '🟢 හිස්',
      'standing_label': '🟡 හිටගෙන',
      'packed_label': '🔴 පිරී ඇත',
      'thanks_reporting': 'සෙනඟ මට්ටම් වාර්තා කිරීම ගැන ස්තූතියි!',
      'passed_label': 'පසු කර ඇත',
      'today_label': 'අද',
      'current_label': 'දැනට පවතින',
      'from_label': 'සිට',
      'to_label': 'දක්වා',
      'next_departure': 'ඊළඟ පිටත්වීම',
      'stop_timeline': 'නැවතුම් කාලරාමුව',
      'no_stops_available': 'නැවතුම් නොමැත',
      'stop_prefix': 'නැවතුම',
      'username_updated': '✓ පරිශීලක නාමය යාවත්කාලීන කරන ලදී',
      'walk_to': 'දක්වා ඇවිදින්න',
      'bus_stand': 'බස් නැවතුම්පොළ',
      'nearest_stop': 'ළඟම ඇති නැවතුම',
      'duration_label': 'කාලය',
      'distance_label': 'දුර',
      'est_fare_label': 'ඇස්තමේන්තුගත ගාස්තුව',
      'nearest_bus_stand': 'ළඟම ඇති බස් නැවතුම්පොළ',
      'min_walk_label': 'මිනිත්තු ඇවිදීම',
      'reported_msg': 'වාර්තා කරන ලදී',
      'failed_report': 'වාර්තාව ඉදිරිපත් කිරීමට අපොහොසත් විය.',
      'status_label': 'තත්ත්වය',
      'heavy_traffic': 'අධික වාහන තදබදය',
      'road_closed': 'මාර්ගය වසා ඇත',
      'overcrowded': 'අධික සෙනඟ',
      'dangerous_driving': 'අන්තරායකර රිය පැදවීම',
      'report_issue_title': 'ගැටලුවක් වාර්තා කරන්න',
      'are_you_sure': 'ඔබට විශ්වාසද?',
      'close': 'වසන්න',
      'minimize': 'හකුළන්න',
      'minimize_ride': 'මාර්ගය හකුළන්න',
      'style_standard': 'සාමාන්‍ය',
      'style_satellite': 'සැටලයිට්',
      'style_minimal': 'සරල',
      'min': 'මිනිත්තු',
      'total': 'සමස්තය',
      'start_trip_btn': 'මාර්ගය අරඹන්න',
      'waiting_at_stops': 'ඊළඟ නැවතුම්වල සිටින මගීන්',
      'stop_ride_btn': 'ගමන නතර කරන්න',
      'stop_ride_confirm_title': 'ගමන නතර කරන්නද?',
      'stop_ride_confirm_msg': 'ඔබට මෙම ගමන නිරීක්ෂණය නතර කිරීමට අවශ්‍ය බව සහතිකද?',
      'search_hint': 'ගමනාන්තය සොයන්න...',
      'suggested_places': 'යෝජිත ස්ථාන',
      'wallet_title': 'පසුම්බිය',
      'wallet_nav': 'පසුම්බිය',
      'available_balance': 'තිබෙන ශේෂය',
      'recent_transactions': 'මෑතකාලීන ගනුදෙනු',
      'top_up': 'පසුම්බිය',
      'passes': 'අවසර පත්‍ර',
      'offers': 'වට්ටම්',
      'pay_for_ride': 'ගාස්තු ගෙවන්න',
      'wallet_info_title': 'TransLink පසුම්බිය',
      'wallet_info_msg': 'TransLink පසුම්බිය මගින් ඔබට QR කේත භාවිතයෙන් බස් ගාස්තු ආරක්ෂිතව ගෙවිය හැකිය. ඔබේ කාඩ්පත් සම්බන්ධ කර ශේෂය පූරණය කළ හැකිය.',
      'voice_assist': 'හඬ සහාය',
      'arriving_in': 'පැමිණීමට තව',
      'min_label': 'මිනි.',
      'quick_actions_title': 'කෙටි ක්‍රියා',
      'passes_title': 'ගමන් අවසර පත්‍ර',
      'school_pass': 'පාසල් / ශිෂ්‍ය අවසර පත්‍රය',
      'train_pass': 'කෝච්චි වාර පත්‍රය',
      'select_pass_type': 'වර්ගය තෝරන්න',
      'buy_pass_btn': 'මිලදී ගන්න',
      'mic_permission_required': 'හඬ සහාය සඳහා මයික්‍රොෆෝනයට අවසර අවශ්‍යයි.',
      'recent_activity': 'මෑත ගනුදෙනු',
      'top_up_method': 'ශේෂය එකතු කිරීමේ ක්‍රමය',
      'link_new_card': 'නව කාඩ්පතක් සම්බන්ධ කරන්න',
      'verified_account': 'සත්‍යාපිත ගිණුම',
      'scan_to_pay': 'ගාස්තු ගෙවීමට ස්කෑන් කරන්න',
      'show_to_conductor': 'කොන්ඩක්ටර්ට පෙන්වන්න',
      'route_details': 'මාර්ග විස්තර',
      'suggested_routes': 'යෝජිත මාර්ග',
      'search_to_see_routes': 'මාර්ග බැලීමට ගමනාන්තයක් සොයන්න',
      'walk_to_bus_stand': 'බස් නැවතුම්පොළට ඇවිදින්න',
      'walk_to_destination': 'ගමනාන්තයට ඇවිදින්න',
      'share_journey': 'ගමන බෙදාගන්න',
      'live_eta': 'සජීවී පැමිණීම',
      'bus_active_msg': 'බස් රථය ක්‍රියාත්මකයි. ලුහුබඳින්න...',
      'upcoming_arrivals': 'පැමිණීමට නියමිත බස්',
      'show_on_map': 'සිතියමේ පෙන්වන්න',
      'eta_label': 'පැමිණීමේ කාලය',
      'on_time': 'නියමිත වේලාවට',
      'delayed': 'ප්‍රමාදයි',
      'cancelled': 'අවලංගුයි',
      'no_upcoming_buses': 'පැමිණීමට නියමිත බස් නොමැත',
      'now_label': 'දැන්',
      'see_all': 'සියල්ල',
      'ai_support': 'AI සහාය',
      'map_view': 'සිතියම',
      'skip_nav': 'මඟහරින්න',
      'next_nav': 'මීළඟ',
      'get_started_nav': 'අරඹමු!',
      // New Onboarding & Fleet
      'select_language': 'භාෂාව තෝරන්න',
      'mixed_fleet': 'මිශ්‍ර බස් සේවය',
      'mixed_fleet_sub': 'පෞද්ගලික සහ ලංගම බස් රථ සජීවීව නිරීක්ෂණය කරන්න.',
      'intercity_express': 'අන්තර් නගර අධිවේගී',
      'intercity_express_sub': 'ශ්‍රී ලංකාව පුරා විශ්වාසදායී දුරගමන් සේවාව.',
      'ctb_label': 'ලංගම',
      'private_label': 'පෞද්ගලික',
      'fleet_status': 'බස් රථ තත්ත්වය',
      'active_buses': 'සක්‍රීය බස් රථ',
      'onboarding_payment_title': 'ඩිජිටල් ගෙවීම්',
      'onboarding_payment_sub': 'QR කේත මගින් පහසුවෙන් ගමන් ගාස්තු ගෙවන්න.',
      'welcome_title': 'TransLink වෙත සාදරයෙන් පිළිගනිමු',
      'welcome_sub': 'ශ්‍රී ලංකාවේ පොදු ප්‍රවාහනය සඳහා ඔබේ හොඳම සහකරු.',
      'starting_from_rs': 'ගාස්තුව රු.',
      'no_stops_found': 'අවට බස් නැවතුම් කිසිවක් සොයා ගැනීමට නොහැකි විය.',
      'm_away': 'මීටර් දුරින්',
      'colombo_matara': 'කොළඹ - මාතර',
      'colombo_galle': 'කොළඹ - ගාල්ල',
      'kaduwela_matara': 'කඩුවෙල - මාතර',
      'makumbura_galle': 'මාකුඹුර - ගාල්ල',
      'colombo_kandy': 'කොළඹ - මහනුවර',
      'payment_success_title': 'ගෙවීම සාර්ථකයි',
      'payment_success_msg': 'මාර්ගය {route} සදහා e-ටිකට්පත නිකුත් කරන ලදී.\\n\\nමෙම ගමන ඔබ අරඹන්නද?',
      'end_journey': 'ගමන අවසන් කරන්න',
      'continue_journey': 'ඉදිරියට යන්න',
      'pay_label': 'ගෙවන්න',
      'login_to_pay_qr': 'ගෙවීම සදහා QR මගින් පිවිසෙන්න',
      'swipe_tracking': 'ගමන විස්තර බැලීමට ඉහලට අදින්න',
      'swipe_route_details': 'මාර්ග විස්තර බැලීමට ඉහලට අදින්න',
      'swipe_nearby': 'අවට බස් සහ නැවතුම් බැලීමට ඉහලට අදින්න',
      'insufficient_balance_msg': 'ප්‍රමාණවත් පසුම්බි ශේෂයක් නොමැත. කරුණාකර මුදල් එකතු කරන්න.',
    },
    'ta': {
      'settings': 'அமைப்புகள்',
      'map_location': 'வரைபடம் மற்றும் இருப்பிடம்',
      'auto_detect': 'தானாகவே இருப்பிடத்தைக் கண்டறி',
      'auto_detect_sub': 'அருகிலுள்ள நிறுத்தங்களை தானாகவே காண்பி',
      'show_virtual_buses': 'மெய்நிகர் பேருந்துகளைக் காண்பி',
      'show_virtual_buses_sub': 'வரைபடத்தில் பேருந்துகளைக் காண்பி',
      'map_style': 'வரைபடம் பாணி',
      'notifications': 'அறிவிப்புகள்',
      'bus_arrival_alerts': 'பேருந்து வருகை அறிவிப்புகள்',
      'bus_arrival_alerts_sub': 'பேருந்து அருகில் வரும்போது அறிவிக்கவும்',
      'app': 'செயலி',
      'language': 'மொழி',
      'about_translink': 'TransLink பற்றி',
      'privacy_policy': 'தனியுரிமைக் கொள்கை',
      'privacy_policy_sub': 'உங்கள் தரவை நாங்கள் எப்படிப் பயன்படுத்துகிறோம்',
      'version': 'பதிப்பு 1.2.0 · இலங்கை',
      'where_to': 'எங்கே செல்ல வேண்டும்?',
      'available_routes': 'கிடைக்கக்கூடிய வழிகள்',
      'home': 'வீடு',
      'work': 'வேலை',
      'recent_searches': 'சமீபத்திய தேடல்கள்',
      'recents': 'சமீபத்தியவை',
      'bus_detected': '🟢 பேருந்து அருகில் உள்ளது',
      'waiting_for_bus': 'பேருந்துக்காக காத்திருக்கிறது...',
      'live': 'நேரடி',
      'waiting': 'காத்திருக்கிறது',
      'schedule_nav': 'அட்டவணை',
      'explore_nav': 'ஆராய்',
      'home_nav': 'வீடு',
      'saved_nav': 'சேமிக்கப்பட்டவை',
      'account_nav': 'கணக்கு',
      'nearby_stops': 'அருகிலுள்ள நிறுத்தங்கள்',
      'quick_actions': 'விரைவான செயல்கள்',
      'active_ride': 'செயலில் உள்ள பயணம்',
      'get_started': 'தொடங்கு',
      'live_tracking': 'நேரடி கண்காணிப்பு',
      'timetables': 'கால அட்டவணைகள்',
      'smart_routes': 'ஸ்மார்ட் வழிகள்',
      'real_time_tracking': 'நிகழ்நேர பொது போக்குவரத்து கண்காணிப்பு',
      'sri_lanka': 'இலங்கை',
      'welcome_back': 'மீண்டும் வருக',
      'sign_in_continue': 'தொடர உள்நுழைக',
      'username': 'பயனர் பெயர்',
      'email_address': 'மின்னஞ்சல் முகவரி',
      'password': 'கடவுச்சொல்',
      'continue_btn': 'தொடரவும்',
      'create_account': 'கணக்கை உருவாக்கு',
      'continue_google': 'Google உடன் தொடர்க',
      'already_have_account': 'ஏற்கனவே கணக்கு உள்ளதா? ',
      'sign_in': 'உள்நுழைய',
      'dont_have_account': "கணக்கு இல்லையா? ",
      'sign_up': 'பதிவு செய்க',
      'enter_email_pass': 'மின்னஞ்சல் மற்றும் கடவுச்சொல்லை உள்ளிடவும்',
      'enter_username': 'பயனர் பெயரை உள்ளிடவும்',
      'something_went_wrong': 'ஏதோ தவறு நடந்துவிட்டது. மீண்டும் முயற்சிக்கவும்.',
      'no_internet_msg': 'இணைய இணைப்பு இல்லை. உங்கள் தரவைச் சரிபார்க்கவும்.',
      'invalid_credentials': 'மின்னஞ்சல் அல்லது கடவுச்சொல் தவறானது. மீண்டும் முயற்சிக்கவும்.',
      'google_login_failed': 'Google உள்நுழைவு தோல்வியடைந்தது. பிறகு முயற்சிக்கவும்.',
      'timeout_msg': 'இணைப்பு நேரம் முடிந்தது. உங்கள் சிக்னலைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
      'permission_denied_msg': 'அனுமதி மறுக்கப்பட்டது. உங்கள் கணக்கு நிலையைச் சரிபார்க்கவும்.',
      'Theme Mode': 'தீம் முறை',
      'sign_out': 'வெளியேறு',
      'profile_info': 'சுயவிவரத் தகவல்',
      'full_name': 'முழு பெயர்',
      'role': 'பங்கு',
      'passenger': 'பயணி',
      'member_since': 'உறுப்பினர் ஆனது',
      'edit_name': 'பெயரை திருத்து',
      'save': 'சேமி',
      'cancel': 'ரத்துசெய்',
      'schedule_saved': 'அட்டவணை மற்றும் சேமிக்கப்பட்டவை',
      'timetable_tab': 'அட்டவணை',
      'saved_routes_tab': 'சேமிக்கப்பட்ட வழிகள்',
      'nearby_bus_stops': 'அருகிலுள்ள பேருந்து நிறுத்தங்கள்',
      'min_walk': 'நிமிட நடை',
      'view_board': 'பலகையைப் பார்க்கவும்',
      'no_stops_nearby': 'அருகில் நிறுத்தங்கள் இல்லை',
      'no_stops_sub': '2 கிமீ தூரத்திற்குள் பேருந்து நிறுத்தங்கள் எதையும் எங்களால் கண்டுபிடிக்க முடியவில்லை.',
      'route_prefix': 'வழி',
      'min_total': 'மொத்த நிமிடம்',
      'search_new_route': 'புதிய வழியைத் தேடு',
      'no_saved_routes': 'சேமிக்கப்பட்ட வழிகள் இல்லை',
      'no_saved_routes_sub': 'சேமிக்க எந்த வழியிலும் இதய ஐகானைத் தட்டவும்.',
      'could_not_open_maps': 'Google Maps ஐத் திறக்க முடியவில்லை',
      'approaching_stop': '🔔 நிறுத்தத்தை நெருங்குகிறது',
      'approaching_stop_msg': 'உங்கள் இலக்கு நிறுத்தத்திலிருந்து 500மீ தொலைவில் உள்ளீர்கள். இறங்கத் தயாராகுங்கள்!',
      'ok': 'சரி',
      'no_transit_options': 'க்கான போக்குவரத்து விருப்பங்கள் இல்லை',
      'retry': 'மீண்டும் முயற்சி செய்',
      'failed_load_routes': 'வழிகளை ஏற்றுவதில் தோல்வி. மீண்டும் முயற்சிக்கவும்.',
      'ride_active_label': 'பயணம் செயலில் உள்ளது',
      'set_label': 'அமை',
      'search_set_home': 'உங்கள் வீட்டு இருப்பிடத்தை அமைக்க தேடவும்',
      'search_set_work': 'உங்கள் வேலை இருப்பிடத்தை அமைக்க தேடவும்',
      'recent_label': 'சமீபத்தியவை',
      'saved_routes_label': 'சேமிக்கப்பட்ட வழிகள்',
      'no_saved_routes_msg': 'இன்னும் சேமிக்கப்பட்ட வழிகள் இல்லை. சேமிக்க இதய ஐகானைத் தட்டவும்.',
      'live_label': 'நேரலை',
      'walk_label': 'நடப்பு',
      'to_stop_label': 'வரை',
      'bus_leg_label': 'பேருந்து',
      'direct_to_dest': 'நேரடியாக இலக்குக்கு',
      'route_text': 'வழி',
      'arrival_label': 'வருகை',
      'no_live_buses': 'தற்போது நேரலை பேருந்துகள் இல்லை',
      'no_active_corridor': 'இந்த பாதையில் செயலில் உள்ள பேருந்துகள் இல்லை',
      'tracking_resume_msg': 'பேருந்து பயணத்தைத் தொடங்கியதும் நேரலை கண்காணிப்பு மீண்டும் தொடங்கும்.',
      'refresh_tracking': 'கண்காணிப்பைப் புதுப்பிக்கவும்',
      'journey_details': 'பயண விவரங்கள்',
      'report_issue': 'பிரச்சினையைப் புகாரளி',
      'set_remind_me': '"Remind Me" எச்சரிக்கையை அமை',
      'cancel_remind_me': '"Remind Me" எச்சரிக்கையை ரத்துசெய்',
      'alight_alert_set': 'இலக்குக்கு 500மீ முன்னதாக நினைவூட்டல் அமைக்கப்பட்டது.',
      'bus_approaching_pickup': 'பேருந்து உங்கள் நிறுத்தத்தை நெருங்குகிறது',
      'dest_near_msg': 'உங்கள் இலக்கு 500மீ தூரத்திற்குள் உள்ளது',
      'how_crowded': 'உங்கள் பேருந்தில் கூட்டம் எவ்வளவு?',
      'empty_label': '🟢 காலியாக உள்ளது',
      'standing_label': '🟡 நின்றுகொண்டு',
      'packed_label': '🔴 நிறைந்துள்ளது',
      'thanks_reporting': 'கூட்ட நிலைகளைப் புகாரளித்ததற்கு நன்றி!',
      'passed_label': 'கடந்துவிட்டது',
      'today_label': 'இன்று',
      'current_label': 'தற்போதைய',
      'from_label': 'இருந்து',
      'to_label': 'வரை',
      'next_departure': 'அடுத்த புறப்பாடு',
      'stop_timeline': 'நிறுத்த காலவரிசை',
      'no_stops_available': 'நிறுத்தங்கள் இல்லை',
      'stop_prefix': 'நிறுத்தம்',
      'username_updated': '✓ பயனர் பெயர் புதுப்பிக்கப்பட்டது',
      'walk_to': 'வரை நடக்கவும்',
      'bus_stand': 'பேருந்து நிலையம்',
      'nearest_stop': 'அருகிலுள்ள நிறுத்தம்',
      'duration_label': 'காலம்',
      'distance_label': 'தூரம்',
      'est_fare_label': 'மதிப்பிடப்பட்ட கட்டணம்',
      'nearest_bus_stand': 'அருகிலுள்ள பேருந்து நிலையம்',
      'min_walk_label': 'நிமிட நடை',
      'reported_msg': 'புகாரளிக்கப்பட்டது',
      'failed_report': 'புகாரைச் சமர்ப்பிப்பதில் தோல்வி.',
      'status_label': 'நிலை',
      'heavy_traffic': 'அதிக போக்குவரத்து',
      'road_closed': 'சாலை மூடப்பட்டுள்ளது',
      'overcrowded': 'அதிக கூட்டம்',
      'dangerous_driving': 'ஆபத்தான வாகனம் ஓட்டுதல்',
      'report_issue_title': 'பிரச்சினையைப் புகாரளி',
      'are_you_sure': 'நிச்சயமாகவா?',
      'close': 'மூடு',
      'minimize': 'சுருக்கவும்',
      'minimize_ride': 'பயணத்தை சுருக்கவும்',
      'style_standard': 'சாதாரண',
      'style_satellite': 'செயற்கைக்கோள்',
      'style_minimal': 'எளிமையான',
      'min': 'நிமிடம்',
      'total': 'மொத்தம்',
      'start_trip_btn': 'பயணத்தை தொடங்கு',
      'waiting_at_stops': 'அடுத்த நிறுத்தங்களில் காத்திருக்கும் பயணிகள்',
      'stop_ride_btn': 'பயணத்தை நிறுத்து',
      'stop_ride_confirm_title': 'பயணத்தை நிறுத்தவா?',
      'stop_ride_confirm_msg': 'இந்த பயணத்தை கண்காணிப்பதை நிறுத்த விரும்புகிறீர்களா?',
      'search_hint': 'இலக்கைத் தேடுங்கள்...',
      'suggested_places': 'பரிந்துரைக்கப்பட்ட இடங்கள்',
      'wallet_title': 'வாலட்',
      'wallet_nav': 'வாலட்',
      'available_balance': 'கிடைக்கக்கூடிய இருப்பு',
      'recent_transactions': 'சமீபத்திய பரிமாற்றங்கள்',
      'top_up': 'டாப் அப்',
      'passes': 'பாஸ்கள்',
      'offers': 'சலுகைகள்',
      'pay_for_ride': 'கட்டணம் செலுத்துங்கள்',
      'wallet_info_title': 'TransLink வாலட்',
      'wallet_info_msg': 'TransLink வாலட் மூலம் கியூஆர் குறியீடுகளைப் பயன்படுத்தி பாதுகாப்பாகப் பயணக் கட்டணத்தைச் செலுத்தலாம். கார்டுகளை இணைத்து பணத்தை ஏற்றிக்கொள்ளலாம்.',
      'voice_assist': 'குரல் உதவி',
      'arriving_in': 'வருகிறது',
      'min_label': 'நிமி',
      'quick_actions_title': 'விரைவான செயல்கள்',
      'passes_title': 'பயண பாஸ்கள்',
      'school_pass': 'பள்ளி / மாணவர் பாஸ்',
      'train_pass': 'மாதாந்திர ரயில் பாஸ்',
      'select_pass_type': 'பாஸ் வகையைத் தேர்ந்தெடுக்கவும்',
      'buy_pass_btn': 'பாஸ் வாங்கவும்',
      'mic_permission_required': 'குரல் உதவிக்கு மைக்ரோஃபோன் அனுமதி தேவை.',
      'recent_activity': 'சமீபத்திய செயல்பாடு',
      'top_up_method': 'டாப் அப் முறை',
      'link_new_card': 'புதிய அட்டையை இணை',
      'verified_account': 'சரிபார்க்கப்பட்ட கணக்கு',
      'scan_to_pay': 'கட்டணம் செலுத்த ஸ்கேன் செய்யுங்கள்',
      'show_to_conductor': 'நடத்துனரிடம் காண்பியுங்கள்',
      'route_details': 'வழி விவரங்கள்',
      'suggested_routes': 'பரிந்துரைக்கப்பட்ட வழிகள்',
      'search_to_see_routes': 'வழிகளைக் காண இலக்கைத் தேடுங்கள்',
      'walk_to_bus_stand': 'பேருந்து நிலையத்திற்கு நடக்கவும்',
      'walk_to_destination': 'இலக்குக்கு நடக்கவும்',
      'share_journey': 'பயணத்தைப் பகிரவும்',
      'live_eta': 'நேரடி வருகை',
      'bus_active_msg': 'பேருந்து செயலில் உள்ளது. கண்காணித்தல்...',
      'upcoming_arrivals': 'வரவிருக்கும் பேருந்துகள்',
      'show_on_map': 'வரைபடத்தில் காண்பி',
      'eta_label': 'வருகை நேரம்',
      'on_time': 'சரியான நேரம்',
      'delayed': 'தாமதம்',
      'cancelled': 'ரத்து செய்யப்பட்டது',
      'no_upcoming_buses': 'வரவிருக்கும் பேருந்துகள் இல்லை',
      'now_label': 'இப்போது',
      'see_all': 'மேலும் காண்க',
      'ai_support': 'AI ஆதரவு',
      'map_view': 'வரைபடம்',
      'skip_nav': 'தவிர்க்க',
      'next_nav': 'அடுத்து',
      'get_started_nav': 'தொடங்குவோம்!',
      // New Onboarding & Fleet
      'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'mixed_fleet': 'கலப்பு கடற்படை',
      'mixed_fleet_sub': 'தனியார் மற்றும் இலங்கை போக்குவரத்து சபை பேருந்துகளை நிகழ்நேரத்தில் கண்காணித்தல்.',
      'intercity_express': 'நகරාන්තර எக்ஸ்பிரஸ்',
      'intercity_express_sub': 'இலங்கை முழுவதும் நம்பகமான நீண்ட தூர பயணம்.',
      'ctb_label': 'இ.போ.ச',
      'private_label': 'தனியார்',
      'fleet_status': 'கடற்படை நிலை',
      'active_buses': 'செயலில் உள்ள பேருந்துகள்',
      'onboarding_payment_title': 'டிஜிட்டல் கட்டணங்கள்',
      'onboarding_payment_sub': 'தொந்தரவு இல்லாத பயணத்திற்கு கியூஆர் குறியீடுகளைப் பயன்படுத்தி ஸ்கேன் செய்து பணம் செலுத்துங்கள்.',
      'welcome_title': 'TransLink இற்கு உங்களை வரவேற்கிறோம்',
      'welcome_sub': 'இலங்கையில் பொதுப் போக்குவரத்துக்கான உங்களின் இறுதித் துணையாக இருக்கும்.',
      'payment_success_title': 'கட்டணம் வெற்றிகரமானது',
      'payment_success_msg': 'வழி {route} க்கான உங்கள் e-டிக்கெட் வெற்றிகரமாக வழங்கப்பட்டது.\\n\\nஇக் பயணத்தை தொடர்ந்து கண்காணிக்க விரும்புகிறீர்களா?',
      'end_journey': 'பயணத்தை முடிக்கவும்',
      'continue_journey': 'தொடரவும்',
      'pay_label': 'கட்டணம்',
      'login_to_pay_qr': 'QR மூலம் கட்டணம் செலுத்த உள்நுழைக',
      'swipe_tracking': 'பயண விவரங்களைக் காண மேலே துழாவுங்கள்',
      'swipe_route_details': 'மார்க்க விவரங்களைக் காண மேலே துழாவுங்கள்',
      'swipe_nearby': 'அருகிலுள்ள பேருந்துகள் மற்றும் நிறுத்தங்களைக் காண மேலே துழாவுங்கள்',
      'insufficient_balance_msg': 'போதிய பணப்பை இருப்பு இல்லை. உங்கள் பணப்பையை நிரப்பவும்.',
    },
  };


  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'si', 'ta'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
