import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'driver_portal': 'Conductor Portal',
      'bus_label': 'Bus',
      'route_label': 'Route',
      'logout': 'Logout',
      'logout_title': 'Log Out?',
      'logout_msg': 'Tracking will stop and your registration will be cleared.\nYou can register again with a new bus or route.',
      'cancel': 'Cancel',
      'live_broadcasting': 'LIVE BROADCASTING',
      'passengers_see_bus': 'Passengers can see your bus',
      'tracking_stopped': 'TRACKING STOPPED',
      'start_tracking_to_resume': 'Tap Start Tracking to resume',
      'outside_hours': 'OUTSIDE OPERATING HOURS',
      'tracking_auto_stopped': 'Tracking auto-stopped',
      'starting': 'STARTING…',
      'connecting_gps': 'Connecting to GPS',
      'bus_short': 'BUS',
      'route_short': 'ROUTE',
      'every_short': 'EVERY',
      'min_label': 'min',
      'route_schedule': 'Route Schedule',
      'route_name': 'Route name',
      'operating_hours': 'Operating hours',
      'frequency': 'Frequency',
      'every_min': 'Every {min} min',
      'last_bus_in': 'Last bus in',
      'auto_note': 'Tracking usually starts automatically. Use the controls above if you need to manage it manually.',
      'manual_controls': 'Manual Controls',
      'tracking_stopped_msg': 'Tracking stopped. Tap Start to resume.',
      'tracking_started_msg': 'Tracking started. Live broadcasting enabled.',
      'conductor_portal': 'Conductor Assistant',
      'on_time': 'On Time',
      'breakdown': 'Breakdown',
      'accident': 'Accident',
      'heavy_traffic': 'Heavy Traffic',
      'medical_emergency': 'Medical Emergency',
      'breakdown_desc': 'Vehicle has broken down and cannot continue.',
      'accident_desc': 'Involved in or blocked by an accident.',
      'medical_emergency_desc': 'Passenger medical emergency onboard.',
      'reported_to_passengers': 'Reported to passengers',
      'reported_msg': '{emoji} "{label}" reported to passengers.',
      'clear': 'Clear',
      'setup_title': 'Bus Registration',
      'setup_sub': 'Register your bus to start broadcasting live location.',
      'enter_bus_number': 'Enter Bus Number',
      'select_route': 'Select Route',
      'register': 'Register & Start',
      'please_fill_all': 'Please fill all fields',
      'language': 'Language',
      'location_permission_required': 'Location Permission Required',
      'location_permission_msg': 'TransLink Conductor needs precise GPS to broadcast your position to passengers. Please allow it in Settings.',
      'gps_is_off': 'GPS is Off',
      'gps_is_off_msg': 'Please enable Location / GPS in your device settings.',
      'reliability_first': 'Reliable Tracking',
      'battery_optimization_msg': 'To ensure passengers can see your bus live even when your screen is locked, please select "Allow" or "No Restrictions" in the next popup.\n\nEssential for Xiaomi, Samsung, and Huawei phones.',
      'ok_understand': 'OK, I Understand',
      'select_fleet': 'Select Fleet',
      'ctb_label': 'CTB',
      'private_label': 'PRIVATE',
      'open_settings': 'Open Settings',
      'register_once_msg': 'Register once. The app will remember your details until you log out.',
      'bus_number_hint': 'e.g. NB-4521',
      'search_route_hint': 'Search route number or name...',
      'no_matching_route': 'No matching route found. You can proceed with this manual entry.',
      'one_time_reg': 'One-time registration',
      'start_route': 'Start Route',
      'stop_route': 'Stop Route',
      'trip_revenue_title': 'Trip Revenue',
      'bus_details_title': 'Bus Details',
      'passengers_count': '{count} Passengers Paid',
      'scan_qr': 'Scan Passenger QR',
      'manual_entry': 'Manual Fare',
      'home_tab': 'Route',
      'revenue_tab': 'Revenue',
      'quick_actions': 'Quick Actions',
      'scan_qr_btn': 'Scan & Pay',
      'stop_route_btn': 'Finish Current Route',
      'start_route_btn': 'Start Live Route',
      'report_issue': 'Report Issue',
      'report_problem': 'Report Problem',
      'view_history': 'View Revenue History',
      'revenue_history': 'Revenue History',
      'no_history': 'No history found.',
      'no_internet': 'No internet connection. Please check your data.',
      'sync_failed': 'Sync failed. Reconnecting...',
    },
    'si': {
      'driver_portal': 'රියදුරු ද්වාරය',
      'bus_label': 'බස් රථය',
      'route_label': 'මාර්ගය',
      'logout': 'ඉවත් වන්න',
      'logout_title': 'ඉවත් වන්නද?',
      'logout_msg': 'ලුහුබැඳීම නතර වන අතර ඔබේ ලියාපදිංචිය ඉවත් කරනු ලැබේ.\nඔබට නව බස් රථයක් හෝ මාර්ගයක් සමඟ නැවත ලියාපදිංචි විය හැක.',
      'cancel': 'අවලංගු කරන්න',
      'live_broadcasting': 'සජීවී විකාශනය',
      'passengers_see_bus': 'මගීන්ට ඔබේ බස් රථය දැක ගත හැක',
      'tracking_stopped': 'ලුහුබැඳීම නතර කර ඇත',
      'start_tracking_to_resume': 'නැවත ආරම්භ කිරීමට "ලුහුබැඳීම ආරම්භ කරන්න" ඔබන්න',
      'outside_hours': 'වැඩ කරන වේලාවෙන් බැහැර',
      'tracking_auto_stopped': 'ලුහුබැඳීම ස්වයංක්‍රීයව නතර විය',
      'starting': 'ආරම්භ වේ…',
      'connecting_gps': 'GPS සමඟ සම්බන්ධ වේ',
      'bus_short': 'බස්',
      'route_short': 'මාර්ගය',
      'every_short': 'සෑම',
      'min_label': 'මිනි.',
      'route_schedule': 'මාර්ග කාලසටහන',
      'route_name': 'මාර්ගයේ නම',
      'operating_hours': 'වැඩ කරන වේලාවන්',
      'frequency': 'වාර ගණන',
      'every_min': 'සෑම මිනිත්තු {min} කට වරක්',
      'last_bus_in': 'අවසාන බස් රථයට තව',
      'auto_note': 'ලුහුබැඳීම සාමාන්‍යයෙන් ස්වයංක්‍රීයව ආරම්භ වේ. ඔබට එය අතින් පාලනය කිරීමට අවශ්‍ය නම් ඉහත පාලන භාවිතා කරන්න.',
      'manual_controls': 'අතින් පාලනය කිරීම්',
      'tracking_stopped_msg': 'ලුහුබැඳීම නතර විය. ආරම්භ කිරීමට "ආරම්භ කරන්න" ඔබන්න.',
      'tracking_started_msg': 'ලුහුබැඳීම ආරම්භ විය. සජීවී විකාශනය ක්‍රියාත්මකයි.',
      'conductor_portal': 'කොන්දොස්තර සහකරු',
      'one_time_reg': 'එක් වරක් ලියාපදිංචි කිරීම',
      'start_route': 'මාර්ගය ආරම්භ කරන්න',
      'stop_route': 'මාර්ගය අවසන් කරන්න',
      'trip_revenue_title': 'ගමන් ආදායම',
      'bus_details_title': 'බස් රථයේ තොරතුරු',
      'passengers_count': 'මගීන් {count} ක් ගෙවා ඇත',
      'scan_qr': 'මගී QR පරිලෝකනය',
      'manual_entry': 'අතින් ඇතුළත් කිරීම',
      'home_tab': 'මාර්ගය',
      'revenue_tab': 'ආදායම',
      'quick_actions': 'ඉක්මන් ක්‍රියා',
      'scan_qr_btn': 'පරිලෝකනය කර ගෙවන්න',
      'stop_route_btn': 'වත්මන් මාර්ගය අවසන් කරන්න',
      'start_route_btn': 'සජීවී මාර්ගය ආරම්භ කරන්න',
      'report_issue': 'ගැටලුවක් වාර්තා කරන්න',
      'report_problem': 'ගැටලුවක් වාර්තා කරන්න',
      'view_history': 'ආදායම් ඉතිහාසය බලන්න',
      'revenue_history': 'ආදායම් ඉතිහාසය',
      'no_history': 'ඉතිහාසයක් නොමැත.',
      'no_internet': 'අන්තර්ජාල සම්බන්ධතාවය පරීක්ෂා කරන්න.',
      'sync_failed': 'සම්බන්ධතාවය අසාර්ථකයි. නැවත උත්සාහ කරයි...',
      'reliability_first': 'ස්ථාවර සම්බන්ධතාවය',
      'battery_optimization_msg': 'ඔබේ දුරකථනයේ තිරය අගුළු දමා ඇති විට පවා මගීන්ට බස් රථය දැකීමට හැකි වන පරිදි, මීළඟ තිරයේ "ඉඩ දෙන්න" (Allow) හෝ "සීමා කිරීම් නැත" (No Restrictions) යන්න තෝරන්න.\n\nXiaomi, Samsung සහ Huawei දුරකථන සඳහා මෙය අත්‍යවශ්‍ය වේ.',
      'select_fleet': 'බස් රථ වර්ගය තෝරන්න',
      'ctb_label': 'ලංගම (CTB)',
      'private_label': 'පෞද්ගලික (PRIVATE)',
    },
    'ta': {
      'driver_portal': 'ஓட்டுநர் போர்டல்',
      'bus_label': 'பேருந்து',
      'route_label': 'வழித்தடம்',
      'logout': 'வெளியேறு',
      'logout_title': 'வெளியேறவா?',
      'logout_msg': 'கண்காணிப்பு நிறுத்தப்படும் மற்றும் உங்கள் பதிவு நீக்கப்படும்.\nநீங்கள் புதிய பேருந்து அல்லது வழித்தடத்துடன் மீண்டும் பதிவு செய்யலாம்.',
      'cancel': 'ரத்துசெய்',
      'live_broadcasting': 'நேரடி ஒளிபரப்பு',
      'passengers_see_bus': 'பயணிகள் உங்கள் பேருந்தைக் காணலாம்',
      'tracking_stopped': 'கண்காணிப்பு நிறுத்தப்பட்டது',
      'start_tracking_to_resume': 'மீண்டும் தொடங்க "கண்காணிப்பைத் தொடங்கு" என்பதைத் தட்டவும்',
      'outside_hours': 'இயக்க நேரத்திற்கு வெளியே',
      'tracking_auto_stopped': 'கண்காணிப்பு தானாகவே நிறுத்தப்பட்டது',
      'starting': 'தொடங்குகிறது…',
      'connecting_gps': 'GPS உடன் இணைக்கப்படுகிறது',
      'bus_short': 'பேருந்து',
      'route_short': 'வழி',
      'every_short': 'ஒவ்வொரு',
      'min_label': 'நிமி.',
      'route_schedule': 'வழித்தட கால அட்டவணை',
      'route_name': 'வழித்தடத்தின் பெயர்',
      'operating_hours': 'இயக்க நேரம்',
      'frequency': 'அதிர்வெண்',
      'every_min': 'ஒவ்வொரு {min} நிமிடங்களுக்கும்',
      'last_bus_in': 'கடைசி பேருந்து இன்னும்',
      'auto_note': 'கண்காணிப்பு பொதுவாக தானாகவே தொடங்கும். நீங்கள் அதை கைமுறையாக நிர்வகிக்க வேண்டும் என்றால் மேலே உள்ள கட்டுப்பாடுகளைப் பயன்படுத்தவும்.',
      'manual_controls': 'கைமுறை கட்டுப்பாடுகள்',
      'tracking_stopped_msg': 'கண்காணிப்பு நிறுத்தப்பட்டது. தொடங்க "தொடங்கு" என்பதைத் தட்டவும்.',
      'tracking_started_msg': 'கண்கාணிப்பு தொடங்கப்பட்டது. நேரடி ஒளிபரப்பு இயக்கப்பட்டது.',
      'conductor_portal': 'நடத்துனர் உதவியாளர்',
      'one_time_reg': 'ஒருமுறை பதிவு செய்தல்',
      'start_route': 'வழியைத் தொடங்கு',
      'stop_route': 'வழியை நிறுத்து',
      'trip_revenue_title': 'பயண வருவாய்',
      'bus_details_title': 'பேருந்து விவரங்கள்',
      'passengers_count': '{count} பயணிகள் பணம் செலுத்தியுள்ளனர்',
      'scan_qr': 'பயண QR ஸ்கேன்',
      'manual_entry': 'கைமுறை பதிவு',
      'home_tab': 'வழித்தடம்',
      'revenue_tab': 'வருவாய்',
      'quick_actions': 'விரைவான செயல்கள்',
      'scan_qr_btn': 'ஸ்கேன் செய்து பணம் செலுத்துங்கள்',
      'stop_route_btn': 'தற்போதைய வழியை முடிக்கவும்',
      'start_route_btn': 'நேரடி வழியைத் தொடங்குங்கள்',
      'report_issue': 'சிக்கலைப் புகாரளிக்கவும்',
      'report_problem': 'சிக்கலைப் புகாரளிக்கவும்',
      'view_history': 'வருவாய் வரலாற்றைக் காண்க',
      'revenue_history': 'வருவாய் வரலாறு',
      'no_history': 'எந்த வரலாறும் கிடைக்கவில்லை.',
      'no_internet': 'இணைய இணைப்பு இல்லை. உங்கள் தரவைச் சரிபார்க்கவும்.',
      'sync_failed': 'ஒத்திசைவு தோல்வியடைந்தது. மீண்டும் இணைக்கிறது...',
      'reliability_first': 'நிலையான கண்காணிப்பு',
      'battery_optimization_msg': 'உங்கள் திரை பூட்டப்பட்டிருந்தாலும் பயணிகள் உங்கள் பேருந்தைக் காண முடியும் என்பதை உறுதிப்படுத்த, அடுத்த திரையில் "அனுமதி" (Allow) அல்லது "கட்டுப்பாடுகள் இல்லை" (No Restrictions) என்பதைத் தேர்ந்தெடுக்கவும்.\n\nXiaomi, Samsung மற்றும் Huawei தொலைபேசிகளுக்கு இது அவசியம்.',
      'select_fleet': 'படை வகை தேர்ந்தெடுக்கவும்',
      'ctb_label': 'CTB',
      'private_label': 'தனியார்',
    },
  };

  String translate(String key, {Map<String, String>? args}) {
    String value = _localizedValues[locale.languageCode]?[key] ?? 
                   _localizedValues['en']?[key] ?? 
                   key;
    if (args != null) {
      args.forEach((k, v) {
        value = value.replaceAll('{$k}', v);
      });
    }
    return value;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();
  @override
  bool isSupported(Locale locale) => ['en', 'si', 'ta'].contains(locale.languageCode);
  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);
  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
